//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPWhoIs
    {
        public string IP { get; set; }
        public Nullable<bool> success { get; set; }
        public string type { get; set; }
        public string continent { get; set; }
        public string continent_code { get; set; }
        public string country { get; set; }
        public string country_code { get; set; }
        public string country_flag { get; set; }
        public string country_capital { get; set; }
        public string country_phone { get; set; }
        public string country_neighbours { get; set; }
        public string region { get; set; }
        public string city { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<double> longitude { get; set; }
        public string asn { get; set; }
        public string org { get; set; }
        public string isp { get; set; }
        public string timezone { get; set; }
        public string timezone_name { get; set; }
        public Nullable<int> timezone_dstOffset { get; set; }
        public Nullable<int> timezone_gmtOffset { get; set; }
        public string timezone_gmt { get; set; }
        public string currency { get; set; }
        public string currency_code { get; set; }
        public string currency_symbol { get; set; }
        public Nullable<double> currency_rates { get; set; }
        public byte[] currency_plural { get; set; }
        public Nullable<bool> favorite { get; set; }
    }
}
